# Generated by Django 4.0.3 on 2022-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.IntegerField()),
                ('studentname', models.CharField(max_length=40)),
                ('studentBranch', models.CharField(max_length=80)),
                ('studentyear', models.IntegerField()),
            ],
        ),
    ]
